stages:
  # Stage 1: Data Preprocessing
  preprocess:
    cmd: ..\.venv-train\Scripts\python.exe 1_eda_and_preprocessing.py  # \ on windows
    wdir: notebooks
    deps:
      - ../data/h251.sas7bdat                        # Raw data source
      - 1_eda_and_preprocessing.py                   # Pipeline call and additional data preparation steps
      - ../src/pipeline.py                           # Preprocessing pipeline
      - ../src/transformers.py                       # Custom transformers
      - ../src/constants.py                          # Feature lists, label mappings, etc.
      - ../src/utils.py                              # Helper functions
    outs:
      - ../data/training_data_preprocessed.parquet
      - ../data/validation_data_preprocessed.parquet
      - ../data/test_data_preprocessed.parquet

  # Stage 2: Modeling
  train:
    cmd: ..\.venv-train\Scripts\python.exe 2_modeling.py
    wdir: notebooks
    deps:
      - ../data/training_data_preprocessed.parquet   # Dependency on Stage 1
      - ../data/validation_data_preprocessed.parquet # Dependency on Stage 1
      - ../data/test_data_preprocessed.parquet       # Dependency on Stage 1
      - 2_modeling.py                                # Training script
      - ../src/constants.py                          # Feature lists, label mappings, etc.
      - ../src/utils.py                              # Helper functions
    outs:
      - ../models/baselines.joblib
